[env.docker]
RUST_LOG="debug"
#RUST_BACKTRACE="1"
DATABASE_URL="${DATABASE_URL}"
BACKEND_URL="${BACKEND_URL}"
BACKEND_PORT="${BACKEND_PORT}"

[env.release]
RUST_LOG="info"
DATABASE_URL="${DATABASE_URL}"
BACKEND_URL="${BACKEND_URL}"
BACKEND_PORT="${BACKEND_PORT}"

[config]
default_to_workspace = false

[tasks.backend-run]
command = "cargo"
args = ["run", "-p", "backend"]

[tasks.backend-build]
command = "cargo"
args = ["build", "--release", "-p", "backend"]

[tasks.frontend-run]
command = "trunk"
args = ["serve", "--address", "0.0.0.0", "--dist", "./target/dist", "./frontend/index.html"]

[tasks.frontend-build]
command = "trunk"
args = ["build", "--release", "--dist", "./dist", "./frontend/index.html"]

[tasks.db-migration]
command = "diesel"
args = ["migration", "run"]

[tasks.db-redo]
command = "diesel"
args = ["migration", "redo"]

[tasks.db-prepare]
command = "cargo"
args = ["sqlx", "prepare", "--", "-p", "backend"]

[tasks.dev]
dependencies = ["backend-run"]
